### ISSUE TITLE
vclog-1.9.1/lib/vclog/report.rb:124:in `read': can't convert nil into String (TypeError)

### ISSUE THREAD

**Issue by phallstrom** [rubyworks/vclog#14]
Ruby 1.8.7-352... just installed the gem into my gemset in a normal git project.  I'd dig into it, but can't right now, but at least this will remind me...

```$ vclog --debug
/Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/lib/vclog/report.rb:117: warning: Object#type is deprecated; use Object#class
/Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/lib/vclog/report.rb:122: warning: Object#type is deprecated; use Object#class
Exception`TypeError' at /Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/lib/vclog/report.rb:124 - can't convert nil into String
Exception `TypeError' at /Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/lib/vclog/cli/abstract.rb:22 - can't convert nil into String
/Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/lib/vclog/report.rb:124:in`read': can't convert nil into String (TypeError)
        from /Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/lib/vclog/report.rb:124:in `print'
        from /Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/lib/vclog/repo.rb:223:in`report'
        from /Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/lib/vclog/cli/log.rb:81:in `execute'
        from /Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/lib/vclog/cli/abstract.rb:77:in`run'
        from /Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/lib/vclog/cli/abstract.rb:19:in `run'
        from /Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/gems/vclog-1.9.1/bin/vclog:5
        from /Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/bin/vclog:19:in`load'
        from /Users/philip/.rvm/gems/ruby-1.8.7-p352@ni/bin/vclog:19

```
```

**Comment by spiderbit** [comment]
have the same problem here installed 1. time the vclog tool under ubuntu 11.10 no other gems yet with gem install vclog.

Hope that gets fixed soon, seems like the only really good tool that goes further a quick perl 1 or 5 liner to get a changelog.**\* LOCAL GEMS ***

ansi (1.4.2)
blankslate (2.1.2.4)
confection (0.1.0)
facets (2.9.3)
json (1.6.5)
rdoc (3.12)
vclog (1.9.1)
xml-simple (1.1.1)

**Comment by spiderbit** [comment]
k for me it runs when I manually installed ruby/ruby-gems 1.9.1 and install the gem over that environment.

**Comment by trans** [comment]
For some reason it's not finding the template to generate the output. I'm not sure I've fixed it, but I adjusted the code so that if it does happen again it will output an error that should make it clear what's amiss. I should have the new release out by the end of today.

**Comment by spiderbit** [comment]
```
black@neptun:~/git/mmailer$ vclog
/var/lib/gems/1.8/gems/vclog-1.9.2/lib/vclog/report.rb:63: warning: Object#type is deprecated; use Object#class
undefined local variable or method `tmp_glob' for #<VCLog::Report:0x7f37667f9f28>




black@neptun:~/git/mmailer$ vclog --debug
/var/lib/gems/1.8/gems/vclog-1.9.2/lib/vclog/report.rb:63: warning: Object#type is deprecated; use Object#class
Exception `NameError' at /var/lib/gems/1.8/gems/vclog-1.9.2/lib/vclog/report.rb:135 - undefined local variable or method `tmp_glob' for #<VCLog::Report:0x7f2b6b443b38>
Exception `NameError' at /var/lib/gems/1.8/gems/vclog-1.9.2/lib/vclog/cli/abstract.rb:22 - undefined local variable or method `tmp_glob' for #<VCLog::Report:0x7f2b6b443b38>
/var/lib/gems/1.8/gems/vclog-1.9.2/lib/vclog/report.rb:135:in `print': undefined local variable or method `tmp_glob' for #<VCLog::Report:0x7f2b6b443b38> (NameError)
    from /var/lib/gems/1.8/gems/vclog-1.9.2/lib/vclog/repo.rb:203:in `report'
    from /var/lib/gems/1.8/gems/vclog-1.9.2/lib/vclog/cli/log.rb:81:in `execute'
    from /var/lib/gems/1.8/gems/vclog-1.9.2/lib/vclog/cli/abstract.rb:77:in `run'
    from /var/lib/gems/1.8/gems/vclog-1.9.2/lib/vclog/cli/abstract.rb:19:in `run'
    from /var/lib/gems/1.8/gems/vclog-1.9.2/bin/vclog:5
    from /usr/local/bin/vclog:19:in `load'
    from /usr/local/bin/vclog:19
```

tried it just again installed over gem install vclog ( in Ubuntu precise soon next stable )

**Comment by trans** [comment]
Thanks for reporting. I'll have a look at this soon. -- Looks like this is going to be a debugging week for me. I have a few other projects to do the same for. So, assuming nothing out of the ordinary arises, expect a new release before the end of the week.

**Comment by spiderbit** [comment]
cool thx ;)
